language: java

before_install: 
  - echo "MAVEN_OPTS='-Xmx2048M -Xss128M -XX:+CMSClassUnloadingEnabled -XX:+UseG1GC -XX:-UseGCOverheadLimit'" > ~/.mavenrc

script: mvn -B install -Pintegration

sudo: required

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
      
cache:
  directories:
  - .autoconf
  - $HOME/.m2

